-- local lspconfig = require("lspconfig")
-- local capabilities = require("cmp_nvim_lsp").default_capabilities()

vim.lsp.enable("lua_ls")
vim.lsp.enable("zls")
vim.lsp.enable("pyright")
vim.lsp.enable("dockerls")
vim.lsp.enable("phpactor")
vim.lsp.enable("superhtml")
--vim.lsp.enable("yls")
