-- local lspconfig = require("lspconfig")
-- local capabilities = require("cmp_nvim_lsp").default_capabilities()

vim.lsp.enable("lua_ls")
vim.lsp.enable("zls")
--vim.lsp.enable("pylyzer")
vim.lsp.enable("dockerls")
vim.lsp.enable("clangd")
vim.lsp.enable("lemminx")
vim.lsp.enable("bashls")
vim.lsp.enable("yls")
